### ISSUE TITLE
wrong settings of dts files in the package.json

### ISSUE THREAD

**Issue by LoTwT** [alexzhang1030/code-explorer#2]
## description

wrong settings of dts files in the package.json

- https://publint.dev

<img width="820" alt="image" src="https://github.com/alexzhang1030/code-explorer/assets/50254496/a872a582-a0b3-458b-9bb3-5a3d7848bbe2">

- https://arethetypeswrong.github.io/

<img width="682" alt="image" src="https://github.com/alexzhang1030/code-explorer/assets/50254496/d3d3aa09-89e2-4f06-8476-91f967fa1853">

A correct version of settings using TSUP can refer to [sxzz/unplugin-starter](https://github.com/sxzz/unplugin-starter)

**Comment by alexzhang1030** [comment]
Maybe type: 'module'

**Comment by LoTwT** [comment]
close in [0ff2235](https://github.com/alexzhang1030/code-explorer/commit/0ff2235b6193551ba9f38159900ea4644ef4d6b3)
